### PR TITLE
Modify admin project metadata to reflect newly added fields

### PR DESCRIPTION
**Pull request by katdivyareddy10**
Added fields available on GraphQL to administrative metadata

Screen Shot 2020-05-13 at 9 19 37 AM
Screen Shot 2020-05-13 at 9 19 19 AM

### CODE REVIEW

**Comment by kdid** [comment]
I think we need to separate "Project" and "Ingest Sheet" from that other project stuff (visually or in naming) - since they are not the same project as that other stuff that's right in the same place @davidschober - we talked about this.

**Comment by adamjarling** [comment]
@kdid Agreed.  Looking back on the wireframes, I'm not sure how "Project" wound up in it's own box in the metadata section.  Are the Project form fields just added, the same as an "Ingestion Project"?  Or is this some other type of project metadata?

**Comment by adamjarling** [comment]
@katdivyareddy10 Looking back at https://github.com/nulib/repodev_planning_and_docs/issues/772, there are a bunch of Descriptive metadata form fields listed, which can make use of the Field Array component.  Want to move forward with adding in the additional Descriptive metadata fields listed to the About tab?

**Comment by davidschober** [comment]
I think we should separate out "Ingest Project" and "Ingest Sheet" in a separate box or some other clearly delineated section. We might want to add some kind headers to help with any confusion. 

The other projects "Project Name", "Project Description", "Project Manager", etc are a different set of administrative metadata that I think can be grouped with the the main set of administrative metadata. 

The history on this is that we realized there was a bit of a name collision between "Project Name" and "Project" (ingest project).

**Comment by adamjarling** [comment]
@katdivyareddy10 For now, let's keep all the Project metadata in the Administrative left box, listed alphabetically.  We can (for now) keep "Project / Ingest Sheet" info in the top box, directly under Work title, just to keep it kind of isolated.

When you're done adding all the rest of the fields to the About tab, ping me and I'd like to play around with how to display it most efficiently.

**Comment by katdivyareddy10** [comment]
> @katdivyareddy10 For now, let's keep all the Project metadata in the Administrative left box, listed alphabetically. We can (for now) keep "Project / Ingest Sheet" info in the top box, directly under Work title, just to keep it kind of isolated.
> 
> When you're done adding all the rest of the fields to the About tab, ping me and I'd like to play around with how to display it most efficiently.

Do you want `About` tab ordered alphabetically too? My last commit shows only `descriptiveMetadata` contents with `fieldArray` ordered and the others are mocked and not live.

**Comment by katdivyareddy10** [comment]
@adamjarling just submitted more changes to order fields by name on Work About & Admin tabs. Also moved IngestSheet to `ScreensWork` component. PR & branch ready for your edits!

**Pull request merged**
