### PR TITLE
Implement batch add and delete functionality for controlled and uncontrolled fields

### PR DESCRIPTION
**Pull request by bmquinn**
- Create Meadow.Data.Works.BatchFunctions for updating controlled and uncontrolled fields using PL/SQL functions added in a migration.
- Update Meadow.Batches to use the new batch functions.
- Update GraphQL batch API to include the uncontrolled fields.
- Test all the things.

### CODE REVIEW

**Comment by adamjarling** [comment]
@bmquinn Maybe it's just my machine which is throwing errors again when running Meadow, but I get this after submitting the batch update mutation.  Maybe not related?

image

```
---
[info]  Sent 200 in 5ms
[debug] QUERY OK db=2.6ms idle=1559.1ms
begin []
[debug] QUERY OK db=7.4ms
rollback []
[error] Task #PID<0.1970.0> started from #PID<0.1968.0> terminating
** (ArgumentError) argument error
    :erlang.iolist_to_binary({:error, %Elasticsearch.Exception{col: 22, line: 1, message: "Unknown key for a START_OBJECT in [bool].", query: nil, raw: %{"error" => %{"col" => 22, "line" => 1, "reason" => "Unknown key for a START_OBJECT in [bool].", "root_cause" => [%{"col" => 22, "line" => 1, "reason" => "Unknown key for a START_OBJECT in [bool].", "type" => "parsing_exception"}], "type" => "parsing_exception"}, "status" => 400}, status: 400, type: "parsing_exception"}})
    (jason 1.2.2) lib/jason.ex:55: Jason.decode/2
    (jason 1.2.2) lib/jason.ex:76: Jason.decode!/2
    (meadow 0.1.0) lib/meadow/batches.ex:106: Meadow.Batches.process_updates/3
    (meadow 0.1.0) lib/meadow/batches.ex:22: anonymous fn/3 in Meadow.Batches.batch_update/3
    (ecto_sql 3.4.5) lib/ecto/adapters/sql.ex:875: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
    (db_connection 2.2.2) lib/db_connection.ex:1427: DBConnection.run_transaction/4
    (meadow 0.1.0) lib/meadow/async.ex:28: anonymous fn/3 in Meadow.Async.run_once/3
    (elixir 1.10.4) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (stdlib 3.12.1) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: #Function<0.75078191/0 in Meadow.Async.run_once/3>
    Args: []
[info]  Synchronizing the index...
[debug] QUERY OK db=4.6ms idle=1013.8ms
begin []
[debug] QUERY OK source="index_times" db=4.1ms
```

**Comment by adamjarling** [comment]
I'd say we just merge it in then start building the UI off it and work out the kinks.

**Review by adamjarling — APPROVED** [review]

**Comment by divyareddynu** [comment]
I got the same errors
Screen Shot 2020-10-06 at 12 58 37 PM

**Comment by bmquinn** [comment]
@adamjarling @divyareddynu It looks like your `query` variable is missing the wrapping "query" parameter so it's not a valid Elasticsearch `query_string`, can you try replacing your query variables with something like:

```json
{
  "query": "{\"query\":{\"bool\":{\"must\":[{\"bool\":{\"must\":[{\"bool\":{\"must\":[{\"match\":{\"model.name\":\"Image\"}}]}}]}}]}}}",
  "add": {
    "descriptiveMetadata": {
      "description":"New Test Description",
      "boxNumber": ["23"]
    }
  }
}
```

Thanks for reviewing!

**Review by divyareddynu — APPROVED** [review]

**Pull request merged**
