### PR TITLE
2374 remove yarn

### PR DESCRIPTION
**Pull request by mbklein**
# Summary 

Replace `yarn` with `npm` throughout the entire dev/test/build process

# Specific Changes in this PR
- add an ADR documenting the switch (and the deprecation of ADR 11)
- remove all `yarn.lock` files and replace them with `package-lock.json`
- update GitHub Actions build
- update `Dockerfile`
- update EC2 instance install script
- update `README.md` to change development setup instructions

# Version bump required by the PR

See [Semantic Versioning 2.0.0](https://semver.org/) for help discerning which is required.

- [x] Patch
- [ ] Minor
- [ ] Major

# Steps to Test

```
rm -rf deps _build assets/node_modules priv/nodejs/*/node_modules
```

Then run through the entire Meadow setup process, run the test suite, start the app, and make sure the UI and a small ingest seem to work OK.

# :rocket: Deployment Notes

**Note** - __if you check any of these boxes go to the [(always open) `main` <- `staging` PR](https://github.com/nulib/meadow/pulls) and add detailed notes and instructions to help out others who may end up deploying your changes to production__

- Backward compatible API changes
  - [ ] Database Schema changes
  - [ ] GraphQL API
  - [ ] Elasticsearch API
  - [ ] Ingest Sheet
  - [ ] CSV metadata export/update API
  - [ ] Shared Links export API
- Backwards-incompatible API changes
  - [ ] Database Schema changes
  - [ ] GraphQL API
  - [ ] Elasticsearch API
  - [ ] Ingest Sheet
  - [ ] CSV metadata export/update API
  - [ ] Shared Links export API
- [ ] Requires data migration
- [ ] Requires database triggers disabled during deployment/migration
- [ ] Requires reindex
- [ ] Terraform changes
  - [ ] Adds/requires new or changed Terraform variables
- [ ] Pipeline configuration changes (requires `mix meadow.pipeline.setup` run)
- [ ] Requires new variable added to `miscellany`
- [ ] Specific deployment synchronization instructions with other apps/API's
- [ ] Other specific instructions/tasks

# Tested/Verified
- [ ] End users/stakeholders

### CODE REVIEW

**Review by adamjarling — APPROVED** [review]
Everything seems to build and run fine for me.

**Review by mathewjordan — APPROVED** [review]

**Review by kdid — COMMENTED** [review]
I cloned a fresh copy of Meadow and ran the "Initial Setup" instructions. 

When trying to start the Phoenix server I get

```
module=Phoenix.Endpoint.Watcher [error] Could not start Node.js watcher because script "/Users/karen/Projects/meadow-copy/assets/node_modules/webpack/bin/webpack.js" does not exist. Your Phoenix application is still running, however assets won't be compiled. You may fix this by running "npm install" inside the "assets" directory.
```

**Comment by mbklein** [comment]
Thanks. I’ll do the same and see if it’s the instructions or the code that needs fixing.

**Comment by adamjarling** [comment]
> I cloned a fresh copy of Meadow and ran the "Initial Setup" instructions.
> 
> When trying to start the Phoenix server I get
> 
> ```
> module=Phoenix.Endpoint.Watcher [error] Could not start Node.js watcher because script "/Users/karen/Projects/meadow-copy/assets/node_modules/webpack/bin/webpack.js" does not exist. Your Phoenix application is still running, however assets won't be compiled. You may fix this by running "npm install" inside the "assets" directory.
> ```

Something to do with the `mix assets.install` command?

**Comment by mbklein** [comment]
It turns out `assets/package-lock.json` was being `.gitignore`d, so it wasn't part of the commit, so `mix assets.install` wasn't installing modules in `assets`.

**Review by kdid — APPROVED** [review]

**Pull request merged**
