### PR TITLE
Remove validation progress count and subscription

### PR DESCRIPTION
**Pull request by kdid**
- Gets rid of the (non-working) percent complete progress bar for validation progress and replaces with a simple "spinner" w/out a numerical percentage.
- Removes the validation subscription infrastructure from the UI code and simplifies the components to using the `ingestSheetUpdate` subscription's `status` field
- Removes the `ingestSheetValidationProgress` subscription and the validation notifier from the backend.
  - leaves the `ingestSheetValidationProgress` query intact so you can still find the progress

Screen Shot 2020-11-05 at 10 22 38 AM

### CODE REVIEW

**Comment by adamjarling** [comment]
@kdid I gotta split now, but just tested twice, restarted the server, and seems like it never gets past the progress bar.  If I refresh the page, the validation is complete. 

@divyareddynu Want to check and make sure its not just my environment?

**Comment by kdid** [comment]
Lemme double check, I changed a couple things after I pushed....

**Comment by kdid** [comment]
@adamjarling @divyareddynu - do a `down -v` first if you test it....

**Review by divyareddynu — APPROVED** [review]
I like the generic spinner during validation. It works as expected and also shows works preview fine after completing ingest.

**Comment by mbklein** [comment]
Looks good to me. :+1:

**Review by mbklein — APPROVED** [review]

**Pull request merged**
