### PR TITLE
Fileset form error message bug

### PR DESCRIPTION
**Pull request by divyareddynu**
Screen Shot 2021-02-03 at 9 04 36 AM

### CODE REVIEW

**Review by kdid — CHANGES_REQUESTED** [review]
Can we get rid of "FileSet label" and have just "Label" in the error text? (same for description)

**Comment by adamjarling** [comment]
Since we're in this component, can we update the Error message to lose "FileSet" from the Error messages?   Just make "Description..." and "Label..."

image

**Review by adamjarling — CHANGES_REQUESTED** [review]
Since we're in this component, can we update the Error message to lose "FileSet" from the Error messages?   Just make "Description..." and "Label..."

image

**Review by adamjarling — APPROVED** [review]
Looks great.

**Pull request merged**
