### PR TITLE
Add clear functionality to VTT modal.

### PR DESCRIPTION
**Pull request by mathewjordan**
# Summary 
This pull request adds functionality to clear the WebVTT value in structuralMetadata and set the structuralMetdata to `{}`. The clear button should only be visible if a webVttValue exists. Upon clearing, the modal does not close and instead delivers a message to the user, however, an updateFileSet mutation is sent, clearing the value in structuralMetadata. The user can then choose to close the modal or add a new value.

image

image

### Notes

While clearing the structuralMetadata does occur, the manifest seems to hold onto some knowledge of that fileset ID existing. I'm not sure if this should be handled somehow differently in this pull request OR if it is a related backend oriented issue.

# Specific Changes in this PR
- Adds Clear button that updates structuralMetadata
- Adds Notifications to end user on clear submit

# Version bump required by the PR

See [Semantic Versioning 2.0.0](https://semver.org/) for help discerning which is required.

- [x] Patch
- [ ] Minor
- [ ] Major

# Steps to Test

1. Go to a Video or Audio work.
2. Go to structure Tab
3. Click Edit Structure
4. Add a valid VTT, Submit, REFRESH
5. Click Edit Structure
6. Click Clear, Close, REFRESH

# :rocket: Deployment Notes

**Note** - __if you check any of these boxes go to the [(always open) `main` <- `staging` PR](https://github.com/nulib/meadow/pulls) and add detailed notes and instructions to help out others who may end up deploying your changes to production__

- Backward compatible API changes
  - [ ] Database Schema changes
  - [ ] GraphQL API
  - [ ] Elasticsearch API
  - [ ] Ingest Sheet
  - [ ] CSV metadata export/update API
  - [ ] Shared Links export API
- Backwards-incompatible API changes
  - [ ] Database Schema changes
  - [ ] GraphQL API
  - [ ] Elasticsearch API
  - [ ] Ingest Sheet
  - [ ] CSV metadata export/update API
  - [ ] Shared Links export API
- [ ] Requires data migration
- [ ] Requires database triggers disabled during deployment/migration
- [ ] Requires reindex
- [ ] Terraform changes
  - [ ] Adds/requires new or changed Terraform variables
- [ ] Pipeline configuration changes (requires `mix meadow.pipeline.setup` run)
- [ ] Requires new variable added to `miscellany`
- [ ] Specific deployment synchronization instructions with other apps/API's
- [ ] Other specific instructions/tasks

# Tested/Verified
- [ ] End users/stakeholders

### CODE REVIEW

**Comment by kdid** [comment]
Hey @mathewjordan - it's hard to see what's going on here because of a couple things

- Yes, here is a back end issue https://github.com/nulib/repodev_planning_and_docs/issues/2415 with manifests not getting updated when it's file sets are updated. We broke something recently on the back end. I'd actually like to see if I can fix it and then we could rebase this branch. 
- I opened a separate issue about the extra `updateFileSets` mutation https://github.com/nulib/repodev_planning_and_docs/issues/2475 that's causing all those extra toast popups that are confusing. 

Those issues aside, I do think I see that in this branch we've lost some of the current functionality that we have on staging + production. If you submit/edit/clear the VTT and then reopen the VTT editor on this branch, it doesn't have the new edits. On staging it does. I think this has to do with not updating the Apollo cache after the mutation returns.

**Comment by kdid** [comment]
I'm also having a bit of an issue with the fact that if you clear the VTT with the clear link (which does send the mutation), you remain stuck there with the modal open. But then if you click submit (which it seems maybe as a user like that's what you are supposed to do - clear and then submit) it sends another - but slightly different mutation.

I'm not sure if this is intentional or what the desired flow of clicks is for the user? But it doesn't seem necessary to send more than one mutation.

Screen Shot 2021-11-23 at 12 36 26 PM

Screen Shot 2021-11-23 at 12 36 13 PM

**Comment by mathewjordan** [comment]
> I'm also having a bit of an issue with the fact that if you clear the VTT with the clear link (which does send the mutation), you remain stuck there with the modal open. But then if you click submit (which it seems maybe as a user like that's what you are supposed to do - clear and then submit) it sends another - but slightly different mutation.
> 
> I'm not sure if this is intentional or what the desired flow of clicks is for the user? But it doesn't seem necessary to send more than one mutation?
> 
> Screen Shot 2021-11-23 at 12 36 26 PM
> 
> Screen Shot 2021-11-23 at 12 36 13 PM

@kdid We can absolutely close the modal on click of the Clear button. I was thinking it'd give the user the option to submit a new one, but perhaps that won't occur very often? Clear should block a resubmit of Submit unless the user reenters a valid WebVTT, is it not doing this for you?

**Comment by kdid** [comment]
It does not - that second screenshot above was from the Submit button after clicking clear. 

I can see several ways the flow on this could work. I think there is a case that a user might want to clear the form and then copy paste in new VTT (of course they could also just select all and then hit delete), and there is also the case for blanking it out.

**Comment by mathewjordan** [comment]
> Hey @mathewjordan - it's hard to see what's going on here because of a couple things
> 
>     * Yes, there is a back end issue [IIIF manifest not getting rewritten after dependent file set updates repodev_planning_and_docs#2415](https://github.com/nulib/repodev_planning_and_docs/issues/2415) with manifests not getting updated when it's file sets are updated. We broke something recently on the back end. I'd actually like to see if I can fix it and then we could rebase this branch.
> 
>     * I opened a separate issue about the extra `updateFileSets` mutation [Viewing/Submitting WebVTT on structure tab sends updateFileSets mutation repodev_planning_and_docs#2475](https://github.com/nulib/repodev_planning_and_docs/issues/2475) that's causing all those extra toast popups that are confusing.
> 
> 
> Those issues aside, I do think I see that in this branch we've lost some of the current functionality that we have on staging + production. If you submit/edit/clear the VTT and then reopen the VTT editor on this branch, it doesn't have the new edits. On staging it does. I think this has to do with not updating the Apollo cache after the mutation returns.



> It does not - that second screenshot above was from the Submit button after clicking clear.
> 
> I can see several ways the flow on this could work. I think there is a case that a user might want to clear the form and then copy paste in new VTT (of course they could also just select all and then hit delete), and there is also the case for blanking it out.

Okay. I'm gonna rework a few things. Thanks for the feedback.

**Comment by mathewjordan** [comment]
@kdid Can you give it a review now. I've simplified some of the Clear logic.

-  Renamed _Clear_ to **Delete WebVTT**. I felt this made more semantic sense to what was actually occurring here.
-  Fixed issue where :
>  If you submit/edit/clear the VTT and then reopen the VTT editor on this branch, it doesn't have the new edits. 
- Closed Modal after Delete WebVTT click

**Comment by kdid** [comment]
you've also got some conflicts going on with `package.json` and `package-lock.json files - you may have noticed. Just mentioning.

**Comment by mathewjordan** [comment]
> you've also got some conflicts going on with `package.json` and `package-lock.json files - you may have noticed. Just mentioning.

Yeah, was planning to resolve prior to merge. I think it's just the ReactMediaPlayer version conflicting.

**Comment by kdid** [comment]
Looks better. I will approve once conflicts resolved.

**Review by kdid — APPROVED** [review]

**Pull request merged**
