### PR TITLE
Add default case for 0 filesets

### PR DESCRIPTION
**Pull request by katdivyareddy10**
Screen Shot 2020-08-17 at 3 10 51 PM

### CODE REVIEW

**Comment by kdid** [comment]
@Divya Katpally - on your PR, I'm wondering if we could make it say "Validating file sets" rather than "Ingesting file sets"? This step is pre-ingest. 

(Or maybe just leave that off altogether and just show percentage...)

**Comment by katdivyareddy10** [comment]
> @divya Katpally - on your PR, I'm wondering if we could make it say "Validating file sets" rather than "Ingesting file sets"? This step is pre-ingest.
> 
> (Or maybe just leave that off altogether and just show percentage...)

@adamjarling I like the "Validating file sets" idea, what are your thoughts?

**Comment by adamjarling** [comment]
@katdivyareddy10 Yea, the wording above sounds good to me.

**Comment by adamjarling** [comment]
@katdivyareddy10 Does it seem like we're straying away from making this component generic?  Seems pretty tightly coupled to implementation (it was from the start, now seemingly more so).  Maybe in the future we pass in the message as a prop or something.

**Comment by katdivyareddy10** [comment]
I agree, I tried to do that but realized that this is used only in 2 places and specifically for ingest sheet progress only.

**Pull request merged**
