### PR TITLE
Use Elasticsearch.Index.hot_swap to build, alias and swap the :meadow index

### PR DESCRIPTION
**Pull request by bmquinn**
Closes https://github.com/nulib/repodev_planning_and_docs/issues/481

Relevant docs about `Elasticsearch.Index.hot_swap/2` located here: https://hexdocs.pm/elasticsearch/Elasticsearch.Index.html#hot_swap/2

### CODE REVIEW

**Comment by kdid** [comment]
Does this do a hot swap on every deployment?

**Comment by bmquinn** [comment]
Yep!

**Comment by kdid** [comment]
Why do we want that?

**Comment by bmquinn** [comment]
That's how it's described in the `elasticsearch-elixir`, one example here: https://github.com/danielberkompas/elasticsearch-elixir/blob/master/guides/deployment/distillery.md#deploying-with-distillery

**Comment by mbklein** [comment]
Just for the sake of a documentation trail, here's more information on the [Elasticsearch Reindex API](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-reindex.html), which is what gets called during the hot-swap.

**Pull request merged**
