### PR TITLE
Create Pipeline.Action module and test framework for Actions

### PR DESCRIPTION
**Pull request by mbklein**
This PR:

* adds a `Meadow.Ingest.Pipeline.Action` module/behaviour to serve as a base for Actions
* adds a `Meadow.PipelineCase` module to serve as a testing framework for Actions
* adds tests for `Meadow.Ingest.Pipeline.Action` using `Meadow.PipelineCase`
* adds dev/test configuration for the local SQS/SNS pieces of `devstack`
* resolves nulib/next-generation-repository#1137
* Partially, if not completely, resolves nulib/next-generation-repository#1108

### CODE REVIEW

**Comment by kdid** [comment]
Approving. FYI you connect issues to a PR down at the bottom of this page there is a button...

**Comment by mbklein** [comment]
> FYI you connect issues to a PR down at the bottom of this page there is a button...

I don't see anything in the UI for that. I've always referenced them in the text. Is it on the PR page or the issue page?

**Comment by kdid** [comment]
Weird, you don't see this button down below?

Screen Shot 2019-09-18 at 12 28 39 PM

**Comment by mbklein** [comment]
Nope.

meadow 2019-09-18 12-32-24

**Comment by kdid** [comment]
You have the Zenhub browser extension installed?  I think it's a ZenHub thing not a Github thing right? (Then they are grouped together on the board)

**Comment by mbklein** [comment]
Ohhhh, that explains it. I use Safari by default, including for Github, and the Zenhub extension is in Chrome.

**Pull request merged**
