### PR TITLE
Remove EDTF.js shim in favor of EDTF hex package

### PR DESCRIPTION
**Pull request by mbklein**
# Summary 
Replace the EDTF.js GenServer/Port with the native [EDTF](https://hexdocs.pm/edtf/readme.html) Elixir package.

# Specific Changes in this PR
- Remove NodeJS EDTF stuff
- Add `edtf` dependency

# Version bump required by the PR

See [Semantic Versioning 2.0.0](https://semver.org/) for help discerning which is required.

- [x] Patch
- [ ] Minor
- [ ] Major

# Steps to Test

1. Launch Meadow
2. Do EDTF Things

# :rocket: Deployment Notes

**Note** - __if you check any of these boxes go to the [(always open) `main` <- `staging` PR](https://github.com/nulib/meadow/pulls) and add detailed notes and instructions to help out others who may end up deploying your changes to production__

- Backward compatible API changes
  - [ ] Database Schema changes
  - [ ] GraphQL API
  - [ ] Elasticsearch API
  - [ ] Ingest Sheet
  - [ ] CSV metadata export/update API
  - [ ] Shared Links export API
- Backwards-incompatible API changes
  - [ ] Database Schema changes
  - [ ] GraphQL API
  - [ ] Elasticsearch API
  - [ ] Ingest Sheet
  - [ ] CSV metadata export/update API
  - [ ] Shared Links export API
- [ ] Requires data migration
- [ ] Requires database triggers disabled during deployment/migration
- [ ] Requires reindex
- [ ] Terraform changes
  - [ ] Adds/requires new or changed Terraform variables
- [ ] Pipeline configuration changes (requires `mix meadow.pipeline.setup` run)
- [ ] Requires new variable added to `miscellany`
- [ ] Specific deployment synchronization instructions with other apps/API's
- [ ] Other specific instructions/tasks

# Tested/Verified
- [ ] End users/stakeholders

### CODE REVIEW

**Comment by kdid** [comment]
Is this still in. play @mbklein ?

**Comment by mbklein** [comment]
Yup! Ready to go whenever.

**Comment by kdid** [comment]
@mbklein can you create and/or attach an issue for this? It seems like enough work that it deserves one. Thanks.

**Review by kdid — APPROVED** [review]
Looks great!

**Pull request merged**
