### PR TITLE
Merge recent dependabot updates

### PR DESCRIPTION
**Pull request by mbklein**

### CODE REVIEW

**Comment by mbklein** [comment]
@adamjarling Do any of these test failures make sense to you? Are they easy fixes, or should we back out one of the JS module updates?

**Comment by adamjarling** [comment]
@mbklein Would resolving the conflicts make the tests pass?

**Comment by adamjarling** [comment]
Ah, those failures may have something to do with mocking the `OpenSeadragonViewer`.  Which should  be mocked...  I'll look into it a bit and see if I can see what's going on.

**Comment by adamjarling** [comment]
@mbklein I'm going to push up a fix in a few...

**Comment by adamjarling** [comment]
I'd close this PR w/o merging, and merge in https://github.com/nulib/meadow/compare/dependencies-fix

**Pull request closed without merging**
