### PR TITLE
Add work_type and work_image fields to ingest sheet and validator

### PR DESCRIPTION
**Pull request by mbklein**

### CODE REVIEW

**Comment by kdid** [comment]
@mbklein - it doesn't seem like you've included the Elixir code that supports the functionality? - Bullet point #2 in the issue. (Ex: setting the work image).

**Comment by mbklein** [comment]
Ah, I didn't realize that specific part of the functionality was in scope for this, but it makes sense that it would be. I thought “functionality” just meant making it validate and that actually setting the work properties would be a different task. I'll add it to this one, though.

**Comment by kdid** [comment]
No, we were thinking it was included. We pointed it pretty high and didn't break out a separate issue

**Comment by mbklein** [comment]
There is a test for it, right [here](https://github.com/nulib/meadow/pull/2219/files#diff-6b9d1c701bd7d3d7fcb16b0153cdf1085f6f696ddcfb2d2ee9800436656399a2R29). (Ingest sheet line [here](https://github.com/nulib/meadow/pull/2219/files#diff-0e69111a71a6318694878c27073995dd01e86812514fde6229fc50d0b9568969R4).)

I'll mess with it locally as well.

**Comment by kdid** [comment]
Ok, I think it was my bad. I got it working. It does seem to be allowing a "P" file to be a representative image, which is breaking the work.

**Review by kdid — APPROVED** [review]

**Pull request merged**
