### PR TITLE
Add administrative metadata schema and more descriptive metadata fields to Work

### PR DESCRIPTION
**Pull request by bmquinn**
Fixes https://github.com/nulib/repodev_planning_and_docs/issues/429
- Renames Meadow.Data.Schemas.Work metatada embedded schema to descriptive_metadata
- Adds administrative_metadata embedded schema. Update schemas, tests, queries, and mutations accordingly.

Example mutation you can run in Graphiql:

```
mutation (
      $accession_number: String!
      $work_type: WorkType!
      $visibility: Visibility!
      $administrative_metadata: WorkAdministrativeMetadataInput!
      $descriptive_metadata: WorkDescriptiveMetadataInput!
      ) {
      createWork(
        accessionNumber: $accession_number
        workType: $work_type
        visibility: $visibility
        administrativeMetadata: $administrative_metadata
        descriptiveMetadata: $descriptive_metadata
        )
      {
        id
      }
    }
```
With the query variables:
```
{
  "accession_number": "00000",
  "visibility": "OPEN",
  "work_type": "IMAGE",
  "descriptive_metadata": {
    "title": "Something",
    "description": "Here's a description",
    "keywords": ["keyword1", "keyword2", "keyword3"],
    "nulSubject": ["nulSubject1", "nulSubject2"],
    "technique": "watercolor"
  },
  "administrative_metadata": {
    "preservationLevel": 1, 
    "rightsStatement": "Test rights statement"
  }
}
```

### CODE REVIEW

**Comment by kdid** [comment]
I think it looks good

One thing, 
@bmquinn -  We moved the `gql` files Wormwood uses out of the front end and over to `/test/gql`. - could you move yours there too?

Also, this was what I was thinking with API changes. I think we should fix these before merging. It's probably overkill to involve Adam should be easy updates. 

https://github.com/nulib/meadow/blob/26ae12f9a28e7eadbfcee4754c1e816d319a157d/assets/js/components/IngestSheet/Completed/Download.jsx#L26

https://github.com/nulib/meadow/blob/138db2ae37127cae71dd5f24be81504b3c906f80/assets/js/components/Work/work.query.js#L11

**Comment by bmquinn** [comment]
Thanks @kdid, I moved the `.gql` files, updated the tests, and updated `Download.jsx`. The second link in your comment is a reference to `FileSet` metadata which isn't changing in this PR so I left that one alone.

**Comment by kdid** [comment]
@bmquinn - I didn't do an exhaustive search of where they appear - just found a couple examples. 
I think there are not many. It looks like the work metadata is a few lines down from where the fileSet metadata was in that file.

**Comment by mbklein** [comment]
> The second link in your comment is a reference to `FileSet` metadata which isn't changing in this PR so I left that one alone.

I think the relevant spot is [line 19](https://github.com/nulib/meadow/blob/138db2ae37127cae71dd5f24be81504b3c906f80/assets/js/components/Work/work.query.js#L19)

**Comment by bmquinn** [comment]
@mbklein `work.query.js:19` is one of the diffs in this PR 😄

**Comment by kdid** [comment]
It looks like just: 

- `assets/js/components/IngestSheet/ingestSheet.query.js`
- `assets/js/testing-helpers.js`
- `assets/js/components/Work/List.test.jsx`

**Comment by bmquinn** [comment]
Updated those 3 files, thanks for digging into it there's a lot of moving parts!

**Pull request merged**
