### PR TITLE
Add support for approval and ingest mutations

### PR DESCRIPTION
**Pull request by mbklein**
- Add mutation for ingest sheet approval / kickoff
- Add ingest progress
- Add auditTrail query
- Add audit trail subscriptions

### CODE REVIEW

**Comment by adamjarling** [comment]
@mbklein We're going over the PR and trying to hook it up to see how I'd go about integrating this.  Can you update descriptions on new `subscription` or `query` and any fields which are not obvious so they show up in Graphiql and make sense to new eyes?   For example `IngestProgress` subscription.   Does it measure progress on the Ingest Job itself, a work, fileset ?  Again, don't have it running but just first glance thoughts.

**Comment by kdid** [comment]
@mbklein - The status I was referring to being set to completed was the `status` column in the `ingest_sheets` table.

**Comment by mbklein** [comment]
@adamjarling @kdid I’m sorry; I just saw your comments on the PR. Because it’s been a while since Brendan and I last worked on the ingest code, I wanted to sanity-check my memory of it and figured the easiest way was to try to see the code in action. I wired it up to the existing front end with minimal changes (mostly replacing mocks with live queries, but with some very minor tweaks to field names).

In doing so, I was reminded that we didn't make it all the way there with respect to capturing errors. Errors that happen in the processing pipeline _are_ getting logged, and are accessible to the front end. Work and FileSet creation errors (e.g., due to duplicate accession numbers) are getting raised, and our current structure lacks a perfect way to capture them in the audit history – because there's no work or file set ID to attach them to. I'll create an issue for that.

You were right, @kdid, that we had overlooked the switching of the status in the `ingest_sheets` table. That's been fixed.

I'm not sure the ingest progress bar subscription is ever getting kicked off. The ingest is happening too fast for me to see it on the page, and I don't see any evidence of it in the Network tab of the browser dev tools.

**Comment by kdid** [comment]
@mbklein - So, it looks like what you've implemented is that the Ingest Sheet is  "finished" ("complete") --- and the percent status is 100% -- at the point at which the database objects are created and the ingest pipeline begins, correct?

**Comment by kdid** [comment]
Looks good, suggesting a couple things related to documentation and clarity before merging:

1) Documentation in Absinthe schema for GraphiQL 
 - I'd like to see comments added to the `auditTrail`'s `action`, `notes`, `outcome` and `objectId` fields as to what you could find in them. 
 - For anything that has a set of values (like it looks like `outcome` is `OK`, `ERROR` and `STARTED`) could we do an enum with comments? - so that it looks something like this?
Screen Shot 2019-11-15 at 10 15 48 AM

 - For fields that don't contain anything usable at this point in time - like I'm thinking of `action` which has `Meadow.Ingest.Actions.CopyFileToPreservation` and the `notes` which looks like it contains XML errors. I think leaving them like this is confusing. I'm not sure whether these are things just meant for the backend or whether there's just more work to be done to before they are ready to be consumed by someone, but I'd say either remove them from the schema right now -  or if you don't want to do that at least put a comment in that they are not finished/usable right now. 



2) Tests 

- I've got tests for almost every query/mutation I wrote for graphQL in `test/meadow_web/schema` (If that's not something we should be doing - pls let me know as I spent alot of time doing it). Both the Absinthe book and that PragProg elixir/graphql course had examples for testing the subscription functionality as well. I'd struggled to get that to work but I have a feeling you could...

- What about some tests that might help other people who weren't involved in the coding understand how you were intending this functionality to work? Things that might have covered the setting of the ingest sheet complete status at a certain point or progress bar functionality - that kind of thing. Isn't there some place to put this kind of thing in Elixir/our app? (^^ testing the subscription functionality may go a ways towards doing that.)


3) Remove mock subscription

**Comment by adamjarling** [comment]
@mbklein, did you still want this reviewed?   Or are you still working on it before merging?   Let me know if you'd like me to do anything with it.

**Comment by adamjarling** [comment]
Just looking at the UI, I see 2 quick future items of work (on the success path), that are probably easier done after this gets merged...

Count on progress bar:

image

The approved items seem to be delivered in random order.  Is there any expectation of the user to see items in the same order as the CSV file they were working on?

image

**Comment by mbklein** [comment]
@adamjarling I think I'm OK with the reviews from Karen & Brendan. There wasn't that much on the UI side as far as I know, and whatever is left is stuff that can be tweaked in future iterations.

**Comment by adamjarling** [comment]
@mbklein I'll keep logging comments here, which will help as notes for issues to create... saw the merge tho, looks good.

Do we want to provide any visual of a work/fileset here?  And if so, does it get added someplace in the data coming back? 

What is `work.fileSets[0].metadata.location`?   Is that a usable derivative for UI or something else?

image

**Comment by adamjarling** [comment]
For displaying errors which occur during this process, is that captured in the `IngestSheetRow` type?  As entries in the `errors` array?

image

**Comment by mbklein** [comment]
> Do we want to provide any visual of a work/fileset here? And if so, does it get added someplace in the data coming back?

We can't provide any visuals until the action referenced in [#1102](https://github.com/nulib/next-generation-repository/issues/1102) is done, but yes, that's the idea.

> What is `work.fileSets[0].metadata.location`? Is that a usable derivative for UI or something else?

That's the location of the original master file itself, so it's not usable as an access/view copy in the UI.

**Comment by mbklein** [comment]
> For displaying errors which occur during this process, is that captured in the `IngestSheetRow` type? As entries in the `errors` array?

The `errors` array is for validation errors (which we're already past by this point). The way to get error information for the ingest is to run the `ingestSheetErrors(id: $ingestSheetId)` query and get the list of `ingestSheetError`s back. Very similar to what was in the mock (and which now contains live data) when you click the `Show mock errors` checkbox.

GraphiQL Workspace 2019-12-02 13-29-37

**Comment by adamjarling** [comment]
> The `errors` array is for validation errors (which we're already past by this point). The way to get error information for the ingest is to run the `ingestSheetErrors(id: $ingestSheetId)` query and get the list of `ingestSheetError`s back. Very similar to what was in the mock (and which now contains live data) when you click the `Show mock errors` checkbox.
> 

Great, thanks for the heads up.  Wonder if `IngestSheetWorkErrors`, or something might be a bit more explicit in this case?   Or maybe as the puzzle pieces come together we can keep the GraphQL naming conventions as targeted as possible.  Probably easier to see it all together.

**Pull request merged**
