### PR TITLE
Implement CSV Metadata Update

### PR DESCRIPTION
**Pull request by mbklein**
- resolves nulib/repodev_planning_and_docs#975
- resolves nulib/repodev_planning_and_docs#1298
- resolves nulib/repodev_planning_and_docs#1316

## Testing

Testing this PR can be a little tricky because the CSV Export code hasn't been wired to the front end yet. So you'll have to use `curl` or some other means to download the spreadsheet template.

### Set up your environment for CSV testing

1. `mix ecto.migrate`
2. Make sure you have some data
3. Run the Meadow web server

### Export a CSV

4. Log in
5. Open the GraphQL Playground
6. Use a GraphQL query to get your login token:

    ```
    query {
      me {
        token
      }
    }
    ```

7. Open a new terminal window and do the following:

    ```
    $ MEADOW_COOKIE=[PASTE YOUR LOGIN TOKEN HERE]
    $ curl -vo export.csv  \
          -H "Cookie: _meadow_key=${MEADOW_COOKIE}" \
          -F query='{"query":{"match_all":{}}}' \
          'https://devbox.library.northwestern.edu:3001/api/export/export.csv'

### Run a CSV Update

8. Edit `export.csv` to your liking. Good data, bad data, whatever you want.
9. Upload `export.csv` to a Minio bucket (e.g., `dev-uploads`). (Maybe rename it to `update.csv`. Or don't. Meadow doesn't care.)
10. Back in GraphQL, playground:

    ```
    mutation {
      csvMetadataUpdate(source: "s3://dev-uploads/update.csv"){
        id
        rows
        source
        status
        insertedAt
        startedAt
        updatedAt
        user
      }
    }
    ```

You'll get a job back with a status of `pending`.

11. Use the `csvMetadataUpdateJob` and `csvMetadataUpdateJobs` queries to get job details and status. The job status should change to `complete` within a reasonable amount of time. If you want to see errors, you'll need to add the error object to your field list:

    ```
    query{
      csvMetadataUpdateJobs{
        id
        source
        status
        insertedAt
        startedAt
        updatedAt
        user
        errors{
          row
          errors{
            field
            messages
          }
        }
      }
    }
    ```

### CODE REVIEW

**Comment by mbklein** [comment]
Addresses multiple issues:
- repodev_planning_and_docs#975
- repodev_planning_and_docs#1298
- repodev_planning_and_docs#1316

**Comment by kdid** [comment]
I think I followed the instructions correctly. I did an export. Opened the file and changed one `false` to `foo`

```
[error] #PID<0.4259.0> running MeadowWeb.Endpoint (connection #PID<0.4234.0>, stream id 3) terminated
Server: devbox.library.northwestern.edu:3001 (https)
Request: POST /api/graphiql
** (exit) an exception was raised:
    ** (SystemLimitError) a system limit has been reached
        :erlang.binary_to_atom("stl:http://id.loc.gov/authorities/names/no2011087251 | mrb:http://id.loc.gov/authorities/names/n50053919 | vac:http://id.loc.gov/authorities/names/n79091588 | lil:http://id.loc.gov/authorities/names/n85153068 | mrb:http://id.loc.gov/authorities/names/n78030997", :utf8)
        (elixir 1.10.4) lib/string.ex:2281: String.to_atom/1
        (elixir 1.10.4) lib/enum.ex:1396: Enum."-map/2-lists^map/1-0-"/2
        (elixir 1.10.4) lib/enum.ex:1396: Enum."-map/2-lists^map/1-0-"/2
        (meadow 0.1.0) lib/meadow/data/csv/import.ex:38: Meadow.Data.CSV.Import.read_csv/1
        (meadow 0.1.0) lib/meadow/data/csv/metadata_update_jobs.ex:69: Meadow.Data.CSV.MetadataUpdateJobs.validate_source/2
        (meadow 0.1.0) lib/meadow/data/csv/metadata_update_jobs.ex:40: Meadow.Data.CSV.MetadataUpdateJobs.create_job/1
        (meadow 0.1.0) lib/meadow_web/resolvers/csv_metadata_update_jobs.ex:16: MeadowWeb.Resolvers.Data.CSV.MetadataUpdateJobs.update/3
        (absinthe 1.5.5) lib/absinthe/resolution.ex:209: Absinthe.Resolution.call/2
        (absinthe 1.5.5) lib/absinthe/phase/document/execution/resolution.ex:230: Absinthe.Phase.Document.Execution.Resolution.reduce_resolution/1
        (absinthe 1.5.5) lib/absinthe/phase/document/execution/resolution.ex:185: Absinthe.Phase.Document.Execution.Resolution.do_resolve_field/3
        (absinthe 1.5.5) lib/absinthe/phase/document/execution/resolution.ex:170: Absinthe.Phase.Document.Execution.Resolution.do_resolve_fields/6
        (absinthe 1.5.5) lib/absinthe/phase/document/execution/resolution.ex:88: Absinthe.Phase.Document.Execution.Resolution.walk_result/5
        (absinthe 1.5.5) lib/absinthe/phase/document/execution/resolution.ex:67: Absinthe.Phase.Document.Execution.Resolution.perform_resolution/3
        (absinthe 1.5.5) lib/absinthe/phase/document/execution/resolution.ex:24: Absinthe.Phase.Document.Execution.Resolution.resolve_current/3
        (absinthe 1.5.5) lib/absinthe/pipeline.ex:369: Absinthe.Pipeline.run_phase/3
        (absinthe_plug 1.5.2) lib/absinthe/plug.ex:488: Absinthe.Plug.run_query/4
        (absinthe_plug 1.5.2) lib/absinthe/plug.ex:268: Absinthe.Plug.call/2
        (phoenix 1.5.7) lib/phoenix/router/route.ex:41: Phoenix.Router.Route.call/2
        (phoenix 1.5.7) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2
```

**Comment by kdid** [comment]
I'm thinking it might make sense to follow our pattern for Ingest Sheet and File Set uploads and add the CSVMetadataImport type to the GraphQL  getPresignedUrl mutation and give it a special place in the uploads bucket?

https://github.com/nulib/meadow/blob/deploy/staging/lib/meadow/utils/aws.ex#L6

Screen Shot 2020-12-22 at 2 53 03 PM

**Comment by kdid** [comment]
I tried the same thing I did before. I changed one `false` to `foo` - I thought that would test the validation but the GraphQL mutation returned pending and the job went to complete w/out error. I did see a warning in the Elixir log though.



```
id,accession_number,collection_id,published,visibility,library_unit,preservation_level,project_name,project_desc,project_proposer,project_manager,project_task_number,project_cycle,status,abstract,alternate_title,ark,box_name,box_number,caption,catalog_key,citation,description,folder_name,folder_number,identifier,keywords,legacy_identifier,notes,terms_of_use,physical_description_material,physical_description_size,provenance,publisher,related_material,rights_holder,scope_and_contents,series,source,table_of_contents,title,license,rights_statement,contributor,creator,genre,language,location,style_period,subject,technique,date_created,related_url
6270ba9e-fb1d-42fe-93e7-96e4add3ba8b,inu-fava-5145147,,foo,RESTRICTED,,,,,,,,,,,,ark:/99999/fk417760438,,,,,,,,,,,,,,,,,,,,,,,,Voluptas est voluptatum unde dolor possimus officia blanditiis delectus.,,,lil:http://id.loc.gov/authorities/names/n85153068 | lil:http://id.loc.gov/authorities/names/n83175996 | pbl:http://id.loc.gov/authorities/names/n50053919,http://vocab.getty.edu/ulan/500029268 | http://vocab.getty.edu/ulan/500030701 | http://vocab.getty.edu/ulan/500102192,http://vocab.getty.edu/aat/300026031 | http://vocab.getty.edu/aat/300056462 | http://vocab.getty.edu/aat/300266117,http://id.loc.gov/vocabulary/languages/div | http://id.loc.gov/vocabulary/languages/nia,http://vocab.getty.edu/tgn/7549617 | https://sws.geonames.org/2347283 | https://sws.geonames.org/292932,http://vocab.getty.edu/aat/300378903,GEOGRAPHICAL:http://id.loc.gov/authorities/subjects/sh85076671,http://vocab.getty.edu/aat/300438611 | http://vocab.getty.edu/aat/300435429,,
```



Screen Shot 2020-12-23 at 1 40 03 PM

**Comment by kdid** [comment]
I deleted the role from one of the contributors: changed: `lil:http://id.loc.gov/authorities/names/n83175996` to `http://id.loc.gov/authorities/names/n83175996` and it went ahead and saved it w/out a role:

Screen Shot 2020-12-23 at 2 04 26 PM

**Comment by mbklein** [comment]
Good find. I’m surprised it’s getting past the changeset validation. I’ll fix it up.

**Comment by mbklein** [comment]
Actually, since this isn't specific to this piece of work, I'm going to suggest that this get merged as is and we open a new issue to deal with the fact that `WorkDescriptiveMetadata` doesn't enforce roles on contributors (or subjects, for that matter). For example, I was able to do the same thing using a Batch Update:

```
mutation BatchUpdate($add: BatchAddInput, $delete: BatchDeleteInput, $replace: BatchReplaceInput, $nickname: String, $query: String!) {
  batchUpdate(add: $add, delete: $delete, replace: $replace, query: $query, nickname: $nickname) {
    id
    status
    nickname
  }
}
```

```
{
  "nickname": "My batch",
  "query": "{\"query\":{\"bool\":{\"must\":[{\"bool\":{\"must\":[{\"bool\":{\"must\":[{\"match\":{\"model.name\":\"Image\"}}]}}]}}]}}}",
  "add": {  
    "descriptiveMetadata": {
      "contributor": [
        {"role": null, "term": "http://id.loc.gov/authorities/names/n83175996"}
      ]
    }
  }
}
```

image

**Comment by kdid** [comment]
I'm noticing that it's blanking out `rights_statement` if I just do a straight export including a work with rights_statement values and reimport the sheet, it's losing the rights_statement.

**Comment by mbklein** [comment]
Created nulib/repodev_planning_and_docs#1355 to address the "contributor without role" issue.

**Comment by kdid** [comment]
I'm also noticing issues with pipes (|) in the fields (I tried description). Screenshot of the data before, and after exporting and reimporting the same sheet - second screenshot. (Rights statement also pictured showing the blanking out)

This is what was exported for that record
```
6270ba9e-fb1d-42fe-93e7-96e4add3ba8b,inu-fava-5145147,191f907e-79bc-4305-8826-ea9d229afda9,false,OPEN,MUSIC_LIBRARY,3,,,,,55,joen,DONE,,,ark:/99999/fk417760438,,,,,,one | two | three | four | argh | sdflkajsdf;lakjsdf;lk | nine,,,,,,,one term,,,,,,,,,,,Quick.,,http://rightsstatements.org/vocab/NoC-OKLR/1.0/,lil:http://id.loc.gov/authorities/names/n85153068 | http://id.loc.gov/authorities/names/n83175996 | pbl:http://id.loc.gov/authorities/names/n50053919 | act:info:nul/884cba5e-0561-4a04-928c-313a7bbbc662,http://vocab.getty.edu/ulan/500029268 | http://vocab.getty.edu/ulan/500030701 | http://vocab.getty.edu/ulan/500102192,http://vocab.getty.edu/aat/300026031 | http://vocab.getty.edu/aat/300056462 | http://vocab.getty.edu/aat/300266117,http://id.loc.gov/vocabulary/languages/div | http://id.loc.gov/vocabulary/languages/nia,http://vocab.getty.edu/tgn/7549617 | https://sws.geonames.org/2347283 | https://sws.geonames.org/292932,http://vocab.getty.edu/aat/300378903,GEOGRAPHICAL:http://id.loc.gov/authorities/subjects/sh85076671,http://vocab.getty.edu/aat/300438611 | http://vocab.getty.edu/aat/300435429,~1999 | 191X | 4848,
```


Screen Shot 2020-12-23 at 2 58 23 PM
Screen Shot 2020-12-23 at 2 58 36 PM

**Comment by mbklein** [comment]
> I tried the same thing I did before. I changed one false to foo - I thought that would test the validation but the GraphQL mutation returned pending and the job went to complete w/out error. I did see a warning in the Elixir log though.

This _was_ by design. The import mechanism has [lists of known false and true values](https://github.com/nulib/meadow/blob/975-csv-update/lib/meadow/data/csv/import.ex#L15-L16). Anything that's _not_ one of those values was interpreted as `false` with a warning in the log. I can't remember the rationale for that any more; I've just pushed an update to let values that can't reasonably be interpreted as `true` or `false` fail validation.

**Comment by kdid** [comment]
OK. I didn't realize it was by design, thought it was something I could do to trigger a validation error. 

Minor thing, but I was wondering if you could expose a few more fields through the API so that the front end has enough info to build a meaningful dashboard from it? We had talked about the dashboard being the same as the batch update dashboard. So minimally expose a created at and started (processing at) timestamp. (I would vote for exposing the user at this point as well, like the other dashboard.)

So, I wanted to get an idea of how this worked "at scale" with more than one job, realistic data, etc... 
I loaded 500 sample works in my dev environment (with generated metadata). To try to get a realistic idea of how long this thing might take to process a real spreadsheet (where every single controlled term is not already cached), I altered the code slightly to call Authoritex on every fetch (Clearing Cachex and the db table didn't really do it since we only have a handful of unique terms in the sample data). Even with 500 records I can't get past the validation. It looks like the GraphQL request times out during the fetches. I don't think we can rely on controlled terms being already cached can we? 

I'm out tomorrow - back Tuesday. There is another thing I have a concern about but will need to take a look at it Tuesday.

**Comment by mbklein** [comment]
Ugh. Looks like I'm going to have to move validation into the asynchronous part of the operation and create a new complex GraphQL type for errors. (Right now, errors can be freeform JSON because they're being returned as part of an error response, but success responses aren't allowed to contain freeform JSON unless they're just strings that get decoded on the client, which is gross.)

**Comment by kdid** [comment]
I don't know, is that the best way to go? Or should validation not be responsible for fetching and caching terms as part of validation (just more of a regex check or something?)? (I don't know the best answer to this, just throwing it out there....)

**Comment by mbklein** [comment]
I do think it's the way to go. Validation happens by creating a dummy work changeset, and since controlled vocabulary fetching/validation is part of work validation, it would be a lot more work to skip it than to bite the bullet and do it. It's fine; it just means going back to the first iteration and tweaking the API to match. And I can have `apply` follow directly on from `validate` so there's no change in the flow from the front end's perspective.

**Comment by kdid** [comment]
Running a 500 row update job... It was chugging through all the fetching and it's status is validating. I happened to have another `iex -S mix` window open. Which had been silent for a long time, then all of the sudden it outputted this and started doing some fetching. (the only job I have in my DB is the one running....). It appears both processes are running the same  job. 

Screen Shot 2021-01-08 at 12 53 36 PM

**Comment by kdid** [comment]
Also, about the `source` that's exposed in the `csvMetadataUpdateJobs` query.... I think that's fine to store source and that's what the front end will pass in in the mutation to kick off the job. However the fact that it's in an s3 bucket is completely behind the scenes. The user is only aware of the filename of the file that they uploaded. So for the purpose populating the dashboard with something meaningful to the user, can you expose filename?

**Comment by kdid** [comment]
@mbklein - I (accidentally) submitted a job w/out uploading the file first. And the job went to invalid. After that I submitted a few more jobs. They seemed not to kick off. It looks like the invalid job is still in the active state. Shouldn't setting a job to invalid set it active=false as well? It doesn't look like it will get reset by the reset_stalled method either. I think that's just looking for jobs with validating and processing statuses? (correct me if I'm wrong on that but the jobs never kicked off for me)


Screen Shot 2021-01-12 at 7 49 20 AM


Screen Shot 2021-01-12 at 7 40 41 AM

**Comment by mbklein** [comment]
Yes, going to invalid should reset to `active: false`. I'll see why it isn't.

**Comment by mbklein** [comment]
The [code that sets `status: "invalid"`](https://github.com/nulib/meadow/blob/76d8de4883e9fdf405cffaab9a10ca1f3d475b1c/lib/meadow/data/csv/metadata_update_jobs.ex#L87-L92) should always have been setting `active: false`. Similarly, `reset_stalled` should [also have been setting `active: false`](https://github.com/nulib/meadow/blob/76d8de4883e9fdf405cffaab9a10ca1f3d475b1c/lib/meadow/data/csv/metadata_update_jobs.ex#L199-L205).

I don't know why they weren't, but I just pushed a change that does three things:

* Consolidates updates using `update_job/2`
* Always sets `active: true` for `status: "validating"` and `status: "processing"` and `active: false` for all other statuses (at the changeset level)
* Checks for the existence of the source when the job is submitted instead of waiting for validation to do so

**Comment by kdid** [comment]
I didn't experience these running in order. I put in 5 in a row in order (export.csv, export2.csv, export3.csv, export4.csv and export5.csv) each with different titles. For some reason the second one stuck in the valid state while others passed it up. In the end the changes from the second one were the last applied. 

I'm also seeing many controlled vocab fetching errors which are killing the manifest worker and the index worker. (I'm seeing these in other batch update too). And I think I might be seeing weird behavior upon recovery from those. I'll do show and tell at standup and see if we can figure out a plan. ( I don't think it's necessarily work that needs to be done with this issue, but it seems certainly like work that needs to be done)


Screen Shot 2021-01-13 at 7 58 19 AM
Screen Shot 2021-01-13 at 7 59 41 AM
Screen Shot 2021-01-13 at 8 00 43 AM
Screen Shot 2021-01-13 at 8 04 37 AM

**Comment by kdid** [comment]
I was hoping to give this one last once-over, but I'm still (or again - I thought this was fixed but maybe I'm wrong) seeing an invalid job (I had a bad vocab term in one field) stay stuck `active=true` and jobs behind it are blocked.

**Pull request merged**
