### PR TITLE
Integrate `?as=iiif` Manifests from DC API

### PR DESCRIPTION
**Pull request by mathewjordan**
# Summary 

Meadow now uses DCAPI `as=iiif` manifests rather than it's own internally generated manifests.

# Specific Changes in this PR

 - GraphQL `work` query returns updated manifestUrl
 - `getIiifManifestHeaders` GQL query removed
-  expose `dcapiEndpoint` query in GQL
- Remove IIIF manifest generation & updating code
    - Existing manifests still exist in S3 and are available at existing url's but no further updating will be performed
- Work Screen / Viewer instances 
   - utilizes Clover IIIF Viewer for all work types and Openseadragon React Viewer is removed
   - poll graphql for DC API bearer tokens every 300 seconds
   - request an `etag` header every 10 seconds
   - `etag` used as key in Clover instances

# Version bump required by the PR

See [Semantic Versioning 2.0.0](https://semver.org/) for help discerning which is required.

- [ ] Patch
- [ ] Minor
- [x] Major

# Steps to Test

- In dev make sure to install new assets and dependencies
  - Create some new audio + video works (existing ones may not have transcoded the AV assets - this was a recent Meadow change, you can verify this as manifests would have .m3u8 uri's and you'll have transcoded assets in your streaming bucket rather than the original uploaded file)
- In dev, start your DCAPI through the `https-proxy`
- Verify on work pages (all work types) should now get IIIF manifests from DC API and display in Clover viewer
- Verify etag polling (updates like file set label edits, re-ordering or file set additions/deletions should be reflected in UI/Clover) 
- Verify nothing else is broken
- Verify updates to existing s3 manifests have stopped but existing manifests still available at old url

# :rocket: Deployment Notes

**Note** - __if you check any of these boxes go to the [(always open) `main` <- `staging` PR](https://github.com/nulib/meadow/pulls) and add detailed notes and instructions to help out others who may end up deploying your changes to production__

- Backward compatible API changes
  - [ ] Database Schema changes
  - [x] GraphQL API
  - [ ] Elasticsearch API
  - [ ] Ingest Sheet
  - [ ] CSV metadata export/update API
  - [ ] Shared Links export API
- Backwards-incompatible API changes
  - [ ] Database Schema changes
  - [x] GraphQL API
  - [ ] Elasticsearch API
  - [ ] Ingest Sheet
  - [ ] CSV metadata export/update API
  - [ ] Shared Links export API
- [ ] Requires data migration
- [ ] Requires database triggers disabled during deployment/migration
- [ ] Requires reindex
- [ ] Terraform changes
  - [ ] Adds/requires new or changed Terraform variables
- [ ] Pipeline configuration changes (requires `mix meadow.pipeline.setup` run)
- [ ] Requires new variable added to `miscellany`
- [ ] Specific deployment synchronization instructions with other apps/API's
- [ ] Other specific instructions/tasks

# Tested/Verified
- [ ] End users/stakeholders

### CODE REVIEW

**Review by bmquinn — COMMENTED** [review]
Looks great in my dev environment 👍 
SCR-20230830-opvr

**Review by bmquinn — APPROVED** [review]

**Comment by mbklein** [comment]
The initial load worked fine. Then I made a change to the work and watched it reindex, but the display never updated. As you can see in the screenshots below, the `ETag` changed but there was never another `GET` request for the whole manifest.

SCR-20230831-lvrb

SCR-20230831-lvun

SCR-20230831-lwej

Does changing work metadata not trigger a reload? I figured anything that altered the `ETag` would do it.

**Comment by kdid** [comment]
@mbklein - I just tried and I'm seeing the manifest refresh and visually you can see Clover reload - and I do see another GET. It's not instant - it maybe took 10 seconds. 

Do you need to do a `mix assets.install` to get a new Clover maybe?

**Review by adamjarling — APPROVED** [review]
Tested with @mathewjordan and looking good.

**Pull request merged**
