### PR TITLE
1223 local authority dashboard

### PR DESCRIPTION
**Pull request by adamjarling**
Supports CRUD operations on NUL Local Authorities including the Dashboard:

image

image

image

image

### CODE REVIEW

**Comment by kdid** [comment]
Looks good. Can we add the id to the table so we can tell the difference if they have the same label/hint? 

Screen Shot 2020-12-22 at 2 20 04 PM

**Review by mbklein — APPROVED** [review]
Looks great, works great.

**Comment by adamjarling** [comment]
@kdid Yea, I'll add the `id` into the table

**Review by kdid — APPROVED** [review]

**Comment by kdid** [comment]
I was about to merge but I guess you need to squash and force push first.

**Pull request merged**
