### PR TITLE
Update parsing and rendering of technical metadata for Image and Medi…

### PR DESCRIPTION
**Pull request by adamjarling**
…a work types

image

### CODE REVIEW

**Review by bmquinn — COMMENTED** [review]
Technical metadata looks great!

Screen Shot 2021-06-29 at 4 02 17 PM

I noticed a couple small things when I was testing out the branch:

Got an error when uploading a video in the UI that went away after a refresh:
Screen Shot 2021-06-29 at 4 00 23 PM

Noticed an issue in the preservation tab when the browser wasn't full width:
Screen Shot 2021-06-29 at 4 01 23 PM

**Comment by adamjarling** [comment]
Ah, that error message is still sneaking through eh?   I think I fix it, then make some other adjustments which probably knocks it loose.  I'll fix that. 

The table display issue I think should be another issue itself.   Trying to cram all that data into a table for responsive just doesn't seem practical with real data.  I'll spin off an issue and attach the screenshot.  I've been noticing it too.

**Comment by adamjarling** [comment]
@bmquinn Pushing up some changes now which address the error.  It was happening when creating a File Set for a Work that previously had 0 File Sets.   Put a little helper notification message in for now, and handling the conditions.   Maybe later we can work on some status messaging to the UI (if even necessary).

image

**Review by bmquinn — APPROVED** [review]
Looks great! 👍

**Pull request merged**
