### PR TITLE
UI cleanup for ingest notifications and notification messaging

### PR DESCRIPTION
**Pull request by adamjarling**
Added some icons to the notification messages, removed the distracting blue color, and consolidated the messages in notifications to hopefully make it status more clear for the user.

image

image

image

### CODE REVIEW

**Review by divyareddynu — APPROVED** [review]
Looks good.

**Comment by kdid** [comment]
Confirmation screen for deleting ingest sheet after failed validation says "undefined"

Screen Shot 2020-10-27 at 8 05 50 AM

**Comment by kdid** [comment]
Also, after deletion it drops me back on this page but the ingest sheet isn't removed from the list and the status is empty.

Screen Shot 2020-10-27 at 8 07 00 AM

**Comment by adamjarling** [comment]
@kdid Yea, this PR is literally just for the notifications themselves.   

There's an issue for the `undefined` title when deleting:  https://github.com/nulib/repodev_planning_and_docs/issues/1196, and I'll add the "sheet not being removed" to that issue as it is probably related.  Somehow the local Apollo cache is not getting updated.

**Review by kdid — APPROVED** [review]

**Pull request merged**
