### PR TITLE
Cutover Meadow to V2 indices

### PR DESCRIPTION
**Pull request by adamjarling**
## &#x1F537; &#x1F537; TO DO ON THIS BRANCH BEFORE MERGING  &#x1F537; &#x1F537;

- [x] EDTF date csv export - blocked by: [#meadow/3887](https://github.com/nulib/repodev_planning_and_docs/issues/3887)
- [x] Thumbnails along top of batch edit screen
- [x] Homepage - visibility bar chart lost visibility labels on bottom axis
- [x] Bulk operations select by id's (Batch/csv export/shared links) sending old (v1 style) queries - select all bulk operations are OK
- [x] link into search to view works affected by batch and csv metadata updates, from their respective dashboards are using old v1 field name
- [x] Ingest Sheet and Ingest Project not appearing in facets
- [x] Link into search to view works associated with an ingest sheet is not working

# Summary 

Cuts over Meadow from the v1 (`meadow`) index to the new v2 indices: `dc-v2-work`, `dc-v2-collection` and `dc-v2-file-set`.

# Specific Changes in this PR

- Most updated the Search Results components, and the Homepage queries to pull repository stats.
- Backend configuration for v1 removed
- Batch update, csv export and other associated code updated to use new indices

# Version bump required by the PR

See [Semantic Versioning 2.0.0](https://semver.org/) for help discerning which is required.

- [ ] Patch
- [ ] Minor
- [x] Major

# Steps to Test
Ensure home page stats seem accurate, and that search results load properly, faceting works, and so forth on the Search page.

# :rocket: Deployment Notes

**Note** - __if you check any of these boxes go to the [(always open) `main` <- `staging` PR](https://github.com/nulib/meadow/pulls) and add detailed notes and instructions to help out others who may end up deploying your changes to production__

- Backward compatible API changes
  - [ ] Database Schema changes
  - [ ] GraphQL API
  - [ ] Elasticsearch API
  - [ ] Ingest Sheet
  - [ ] CSV metadata export/update API
  - [ ] Shared Links export API
- Backwards-incompatible API changes
  - [ ] Database Schema changes
  - [ ] GraphQL API
  - [x] Elasticsearch API
  - [ ] Ingest Sheet
  - [ ] CSV metadata export/update API
  - [ ] Shared Links export API
- [ ] Requires data migration
- [ ] Requires database triggers disabled during deployment/migration
- [ ] Requires reindex
- [ ] Terraform changes
  - [ ] Adds/requires new or changed Terraform variables
- [ ] Pipeline configuration changes (requires `mix meadow.pipeline.setup` run)
- [ ] Requires new variable added to `miscellany`
- [ ] Specific deployment synchronization instructions with other apps/API's
- [ ] Other specific instructions/tasks

# Tested/Verified
- [ ] End users/stakeholders

### CODE REVIEW

**Comment by adamjarling** [comment]
### To do:
- Batch Edit, thumbnails not displaying
- Viewing Batch Edited works, needs to change to use the new Batch Id property (maybe same as CSV)
- Batch edits (not all), the index query generated is using old query syntax
- Homepage, bar graph lost labels (Institution, etc.)
-

**Comment by adamjarling** [comment]
@bmquinn @mbklein Hey trying to sort out why Ingest Sheet and Ingest Project aren't populating in the sidebar.  Should these values exist here?   And Project Proposer?

image

**Comment by adamjarling** [comment]
@davidschober Do we want to facet on `title` or `id` for Ingest Project and Ingest Sheet?

image

**Comment by davidschober** [comment]
Title, I believe.

**Comment by mbklein** [comment]
I don't think this PR requires a reindex any more; it's being handled by #3319 by way of #3286

**Review by mbklein — APPROVED** [review]
Everything seems to be working well in my dev environment, and it's all rebased on top of `deploy/staging` and building properly with esbuild.

**Pull request merged**
