### PR TITLE
Add Meadow.Data.FileSets.aspect_ratio/1 and include in indexed work representative file set data

### PR DESCRIPTION
**Pull request by bmquinn**
# Summary 
Adds the ability to calculate aspect ratio data from extracted metadata based on `Meadow.Data.FileSets.height/1` and `Meadow.Data.FileSets.width/1`. Includes this information for use in the front end via the `representative_file_set` data encoded in V2 indexed work documents.

# Specific Changes in this PR
- Add `Meadow.Data.FileSets.aspect_ratio/1`
- Adds to `aspect_ratio` field to `Meadow.Indexing.V2.Work/1`.

# Version bump required by the PR

See [Semantic Versioning 2.0.0](https://semver.org/) for help discerning which is required.

- [x] Patch
- [ ] Minor
- [ ] Major

# Steps to Test
Add a representative file set to a work that contains height and width and check the index:

```
POST [V2 Work Index]/_search
{
  "_source": "representative_file_set.aspect_ratio", 
  "query": {
    "match_all": {}
  },
  "size": 3
}
```

```json
{
  "hits" : {
    "hits" : [
      {
        "_index" : "[V2 Work Index]",
        "_type" : "_doc",
        "_id" : "2485d1ee-950d-457b-af1f-7e3662f941f2",
        "_score" : 1.0,
        "_source" : {
          "representative_file_set" : {
            "aspect_ratio" : 1.366666666666666
          }
        }
      },
      {
        "_index" : "[V2 Work Index]",
        "_type" : "_doc",
        "_id" : "d8376039-49cc-4a11-b4d1-becc4ab06061",
        "_score" : 1.0,
        "_source" : {
          "representative_file_set" : {
            "aspect_ratio" : 1.533595113438045
          }
        }
      },
      {
        "_index" : "[V2 Work Index]",
        "_type" : "_doc",
        "_id" : "21991c2b-0e79-4705-9f66-a929d8919329",
        "_score" : 1.0,
        "_source" : {
          "representative_file_set" : {
            "aspect_ratio" : 0.77968719830083
          }
        }
      }
    ]
  }
}
```

# :rocket: Deployment Notes

**Note** - __if you check any of these boxes go to the [(always open) `main` <- `staging` PR](https://github.com/nulib/meadow/pulls) and add detailed notes and instructions to help out others who may end up deploying your changes to production__

- Backward compatible API changes
  - [ ] Database Schema changes
  - [ ] GraphQL API
  - [X] Elasticsearch API
  - [ ] Ingest Sheet
  - [ ] CSV metadata export/update API
  - [ ] Shared Links export API
- Backwards-incompatible API changes
  - [ ] Database Schema changes
  - [ ] GraphQL API
  - [ ] Elasticsearch API
  - [ ] Ingest Sheet
  - [ ] CSV metadata export/update API
  - [ ] Shared Links export API
- [ ] Requires data migration
- [ ] Requires database triggers disabled during deployment/migration
- [X] Requires reindex
- [ ] Terraform changes
  - [ ] Adds/requires new or changed Terraform variables
- [ ] Pipeline configuration changes (requires `mix meadow.pipeline.setup` run)
- [ ] Requires new variable added to `miscellany`
- [ ] Specific deployment synchronization instructions with other apps/API's
- [ ] Other specific instructions/tasks

# Tested/Verified
- [ ] End users/stakeholders

### CODE REVIEW

**Comment by kdid** [comment]
@bmquinn - I'm getting an error when I try to reindex:

```
** (ArgumentError) cannot perform Ecto.Repo.get/2 because the given value is nil
    (ecto 3.8.4) lib/ecto/repo/queryable.ex:434: Ecto.Repo.Queryable.query_for_get/2
    (ecto 3.8.4) lib/ecto/repo/queryable.ex:69: Ecto.Repo.Queryable.get!/4
    (meadow 7.0.1) lib/meadow/indexing/v2/work.ex:173: Meadow.Indexing.V2.Work.representative_file_set/1
    (meadow 7.0.1) lib/meadow/indexing/v2/work.ex:58: Meadow.Indexing.V2.Work.encode/1
    (elixir 1.13.3) lib/stream.ex:572: anonymous fn/4 in Stream.map/2
    (elixir 1.13.3) lib/enum.ex:4475: Enumerable.List.reduce/3
    (elixir 1.13.3) lib/stream.ex:931: Stream.do_list_transform/7
    (elixir 1.13.3) lib/stream.ex:1719: Enumerable.Stream.do_each/4
    (elixir 1.13.3) lib/stream.ex:880: Stream.do_transform/5
    (elixir 1.13.3) lib/stream.ex:1719: Enumerable.Stream.do_each/4
    (elixir 1.13.3) lib/stream.ex:649: Stream.run/1
    (meadow 7.0.1) lib/meadow/data/indexer.ex:92: anonymous fn/3 in Meadow.Data.Indexer.synchronize_schema/3
    (ecto_sql 3.8.3) lib/ecto/adapters/sql.ex:1222: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
    (db_connection 2.4.2) lib/db_connection.ex:1562: DBConnection.run_transaction/4
    (meadow 7.0.1) lib/meadow/search/client.ex:50: Meadow.Search.Client.perform_hot_swap/2
    (elixir 1.13.3) lib/enum.ex:937: Enum."-each/2-lists^foreach/1-0-"/2
```

**Comment by kdid** [comment]
I'm also just wondering if 15 decimal places is too many? I was expecting two. Discuss.

**Comment by mbklein** [comment]
> I'm also just wondering if 15 decimal places is too many? I was expecting two. Discuss.

I was wondering that as well.

**Comment by mbklein** [comment]
> @bmquinn - I'm getting an error when I try to reindex:
> 
> ```
> ** (ArgumentError) cannot perform Ecto.Repo.get/2 because the given value is nil
> ```

So is the [test suite](https://github.com/nulib/meadow/actions/runs/3397143756/jobs/5650518875#step:17:699)

**Review by kdid — APPROVED** [review]
👍

**Pull request merged**
